global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: breast-cancer-model-serving
    scheme: https
    metrics_path: /monitoring/prometheus/metrics
    static_configs:
      - targets: ["mlops-dicoding-reza-production.up.railway.app:443"]
