global:
  scrape_interval: 15s
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: model-serving
    metrics_path: /monitoring/prometheus/metrics
    static_configs:
      - targets: ["model-serving:8501"]
